### PR TITLE
Fix documentation typos. #3196

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3196

### CODE REVIEW

**Review by jtbx — APPROVED** [review]

**Comment by ChillerDragon** [comment]
Hmm not too sure yet what to do about conflicts. That will become a bigger and bigger problem if the original author is not around.

**Comment by jtbx** [comment]
Ah I could copy the changes onto my own branch and fix the conflicts that way, that would work well no?

**Comment by ChillerDragon** [comment]
> Ah I could copy the changes onto my own branch and fix the conflicts that way, that would work well no?

Yes that would work. The question is how nice that is :D

**Comment by ChillerDragon** [comment]
It is a bit of manual work. And then the question is who to set as git commit author. Ideally it would be the original author. Or at least using githubs [co author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) feature. But that then might offend the original author. That a git conflict was solved badly in his name. Maybe we should decide on a per case basis on how to proceed. On some more complex changes it might be worth it to ping the original author and ask if he is willing to solve conflicts for us. Which is also additional effort for the contributor because those conflicts might not exist on the official repository.

**Comment by jtbx** [comment]
True true. I was going to argue that you could just set the git commit author to the identity of the original author for all cases but yes that doesn't work all the time. I mean it shouldn't really matter for small changes like a copyright year update or a couple of typo fixes but I guess you're right

**Comment by ChillerDragon** [comment]
Yes for small stuff spoofing the author seems the way to go. So if you want to do it for this pr that would be amazing @jtbx

**Comment by jtbx** [comment]
Sure done. #76

**Pull request closed without merging**
