### PR TITLE
Add more sound options for chat #2277

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/2277

### CODE REVIEW

**Comment by ChillerDragon** [comment]
test

**Comment by ChillerDragon** [comment]
The main concern upstream is over configuration. Too many options for users. I personally think that is fine.

I would categorize the change as feature tho. So not really in scope of teeworlds-community. Also it creates config variables which would then not be compatible with teeworlds. But I still think it would be okay to merge it here. No config variables were changed or removed just new ones were added. So teeworlds-community would still correctly understand all teeworlds config files. But teeworlds would no longer understand all config files generated by teeworlds-community. Which I would say is still okay.

In general I would say adding new config variables or commands. Even new UI elements in the settings also as feature. Can be considered in scope of this teeworlds-community project. Especially if it does not touch anything gameplay related.

The author is still around but not sure if he would like to fix conflicts for teeworlds. We can ping him when this got enough approvals. No need to wake him before or recreate the branch.

**Review by ChillerDragon — APPROVED** [review]

**Comment by jtbx** [comment]
> The main concern upstream is over configuration. Too many options for users. I personally think that is fine.

If the default configuration stays the same as the vanilla client then I agree.

> I would categorize the change as feature tho. So not really in scope of teeworlds-community. Also it creates config variables which would then not be compatible with teeworlds. But I still think it would be okay to merge it here. No config variables were changed or removed just new ones were added. So teeworlds-community would still correctly understand all teeworlds config files. But teeworlds would no longer understand all config files generated by teeworlds-community. Which I would say is still okay.
>
> In general I would say adding new config variables or commands. Even new UI elements in the settings also as feature. Can be considered in scope of this teeworlds-community project. Especially if it does not touch anything gameplay related.

Yep I reckon it's fine as long as we can still load teeworlds configs and assets and such.

> The author is still around but not sure if he would like to fix conflicts for teeworlds. We can ping him when this got enough approvals. No need to wake him before or recreate the branch.

I'm sure Ryo won't mind :D

**Review by jtbx — APPROVED** [review]

**Review by BlaiZephyr — APPROVED** [review]
seems like this one is still in scope with teeworlds-community

**Comment by ChillerDragon** [comment]
Moved it to https://github.com/teeworlds-community/teeworlds/pull/106 so we can edit the branch and fix the merge conflicts. (I did not do that yet :D) Maybe we should poke ryo

**Pull request closed without merging**
