### PR TITLE
Fix CStorage::ReadFile #3235

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3235

### CODE REVIEW

**Review by ChillerDragon — CHANGES_REQUESTED** [review]
Might conflict with https://github.com/teeworlds-community/teeworlds/pull/53 I am in favor of merging that instead.

**Comment by Bamcane** [comment]
> Might conflict with #53 I am in favor of merging that instead. 

#53 fixed it? I think a PR must be one of a bug fix and a functional updates, no both.
If a PR do a bug fix and a functional updates both, we may not want to add the functional updates of the PR, isn't it? (Not means #53 is useless)

@ChillerDragon 
Should I close the upstream PR?

**Comment by ChillerDragon** [comment]
> Should I close the upstream PR?

Idk you decide.

**Comment by ChillerDragon** [comment]
And I do like the functional updates of #53. So merging yours would potentially make merging #53 more annoying.

**Comment by Bamcane** [comment]
#53 fixed it, so please don't merge this

**Pull request closed without merging**
