### PR TITLE
Let some scrollbars have out of range values #3252

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3252

### CODE REVIEW

**Review by ChillerDragon — DISMISSED** [review]
This does fix a bug. I am in favor of merging it.

**Comment by ChillerDragon** [comment]
Currently if one sets `inp_mousesense 1000` that works fine in game. But that value will be clamed as soon as the user visits the settings menu where the range is rendered. Opening a menu should never change your settings!

Before the input was hard clamped at 500 now it grows the max to the current value of the config. So in the `inp_mousesense 1000` example the menu now looks like this:

image

**Review by ghost — DISMISSED** [review]

**Comment by ChillerDragon** [comment]
Fetched new commits using `ARG_DRY=0 ./mirror-bot.sh --update 3252`

**Review by ChillerDragon — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by CherryEx — APPROVED** [review]

**Review by jtbx — APPROVED** [review]

**Comment by ChillerDragon** [comment]
I abused org admin to force merge. We got enough approvals but the pipeline is broken. We really need to fix the macos issue https://github.com/teeworlds-community/teeworlds/issues/109

**Pull request merged**
