### PR TITLE
Fix CMP0148 #3212

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3212

### CODE REVIEW

**Review by Bamcane — DISMISSED** [review]

**Review by jtbx — DISMISSED** [review]

**Review by Kaffeine — CHANGES_REQUESTED** [review]
This code is correct but it requires CMake version bump.
Current master:
```
cmake_minimum_required(VERSION 2.8.12...3.19.1)
```
`FindPython3` added in [CMake-3.12](https://cmake.org/cmake/help/latest/release/3.12.html#modules) but it had some bugs/issues with the package detection. On my practice it works reliably only since CMake-3.15.

> [!WARNING]
> We should bump `cmake_minimum_required` at least to 3.12 (better to 3.15) in this MR or before merging this.

Personally I'd add the bump to the PR branch and merge it — CMake supports old systems explicitly with that idea in mind: CMake users should be able to install newer CMake on old systems, and the developers are expected to use one of the latest CMake releases even with old compilers/toolchains/targets.
Anyone (who needs latest teeworlds) can download the latest CMake release build from https://cmake.org/download/.

**Comment by ChillerDragon** [comment]
@Kaffeine I cherry picked your https://github.com/ddnet/ddnet/commit/225b1758894bcf8bccf002476961ab71279e9250 to now match ddnets CMakeLists.txt. I understand that 3.15 is probably more correct. But I would like to keep it low profile on the experiments for now. The 3.12 worked fine in ddnet so far so let's go with that. Until it changes either in ddnet or in teeworlds.

**Comment by Kaffeine** [comment]
> The 3.12 worked fine in ddnet so far

How could you know? Personally I had issues with python3 interpreter not found in some virtual environment (fixed in 3.15: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/3173) and some more bugs I can't recall and reference right now.

But I agree that unification with DDNet worths it.

LGTM :+1:

**Review by Kaffeine — APPROVED** [review]

**Comment by ChillerDragon** [comment]
> How could you know?

I mean ddnet has multiple devs working on it and no open issues regarding cmake version. I would prefer to run into the same issues like ddnet and teeworlds and also propose the fixes there than to create a different code base with new issues.

**Comment by ChillerDragon** [comment]
@Bamcane @jtbx your reviews got invalidated when I sent another change. This pr is the basis for activating more checks to ensure that all future changes we merge actually build.

**Review by ChillerDragon — APPROVED** [review]

**Review by Bamcane — APPROVED** [review]

**Review by ST-Chara — APPROVED** [review]

**Pull request merged**
