### PR TITLE
Add autumn theme (#2668) #2682

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/2682

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Not too sure about this one. I am of course heavily biased because it is my pr. But there were some concerns upstream. A modified version of this has been accepted into ddnet:

screenshot_2024-02-24_18-42-18

So merging this pr as is would differ from ddnet and leave unsolved feedback from the teeworlds core team.
Also it is a feature not a bug fix so technically out of scope of this project imo. But it is a non breaking optional feature.

All in all I think this pr should not become stale here. We can either merge it or close it. There is no gain from keeping it open and waiting on what happens upstream.

**Comment by jtbx** [comment]
If it's ready I say we merge it.

**Comment by ChillerDragon** [comment]
> If it's ready I say we merge it.

Well thats for you to decide. From my side it is ready. But upstream feedback says it should not contain tiles. And also that I should add new mapres. New mapres I would consider out of scope for teeworlds-community.

If you consider it not ready we can just close the pr.

**Comment by jtbx** [comment]
Mmmhh I think the tiles are fine but there needs to be something more autumny, like a new mapres which is out of scope. The theme could easily be mistaken for a spring or summer theme imo.

**Comment by ChillerDragon** [comment]
No idea how to do that without new mapres. Building something cursed with colored quads that should look like leaves sounds horrible.

But I see your point. If the goal is to have themes for all seasons and the season is not easy to see that's wrong. I'd say we just close the pr unless someone has an idea on how to rescue it.

**Comment by ChillerDragon** [comment]
Okay let's close it. I do not want to mess with the art style if there is doubts.

**Pull request closed without merging**
