### PR TITLE
Allow editor switch entities #3236

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3236

### CODE REVIEW

**Comment by ChillerDragon** [comment]
This is a feature. But not touching gameplay, art style, physics, or network protocol. I think this could be merged in teeworlds-community.

**Comment by ChillerDragon** [comment]
Oy expressed his opinion to reject all work done on the editor. In favor of the editor2 project. So this will most likely be rejected upstream. We could use teeworlds-community to keep supporting the deprecated editor and also add new features. It should not really conflict with upstream because the upstream somewhat promised to not touch that code.

On the other hand adding new features increases complexity, compile times and increases the risk of bugs. Is that something we want in a code base that should serve as a stable foundation for modders?

**Comment by tempral** [comment]
this is a small change, I don't see how it can put at risk the robustness of the project

**Comment by ChillerDragon** [comment]
> this is a small change, I don't see how it can put at risk the robustness of the project

Yes this specific change seems stable. I was speaking in general. If we decide to maintain the editor v1 we might as well actively add features but not sure if we should aim for that.

**Comment by jtbx** [comment]
Since editor v2 won't be finished for ages I'd say it's totally
acceptable to allow changes on the current editor.

**Comment by ChillerDragon** [comment]
I rebased the pr on latest community so the pipeline can pass. The pr moved to https://github.com/teeworlds-community/teeworlds/pull/105

**Pull request closed without merging**
