### PR TITLE
ci: use `fail-fast: false` #3231

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3231

### CODE REVIEW

**Review by ChillerDragon — APPROVED** [review]

**Review by Bamcane — APPROVED** [review]

**Review by jtbx — APPROVED** [review]

**Review by GutZuFusss — APPROVED** [review]
lgtm

**Comment by ChillerDragon** [comment]
Is it stuck? Or does it really have to pass the pipeline before merge? That would be annoying. Because basically no pr passes the pipeline before merged into master. That would mean we have to lax the requirement to only require build-bam ubuntu and check-style -.-

I will look into it when I find time.

**Comment by MilkeeyCat** [comment]
dont u have some big boi button like "merge no matter what"?

**Comment by ChillerDragon** [comment]
> dont u have some big boi button like "merge no matter what"?

Even if, that would be very ugly. The branch should be protected by the CI. And merges should not depend on me being active. As far as I can see it now there is no option to require the status check after merge.

@MilkeeyCat as a hotfix you can rebase your branch to latest community and then all pipelines will pass. But that is not really a smooth option for all the other older prs.

**Comment by ChillerDragon** [comment]
Moved to https://github.com/teeworlds-community/teeworlds/pull/96

**Pull request closed without merging**
