### PR TITLE
Add CJsonParser, revise io_read_all/io_read_all_str #3141

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3141

### CODE REVIEW

**Review by ChillerDragon — APPROVED** [review]
LGTM.

**Review by jtbx — APPROVED** [review]
Neat changes, looks good. Also builds fine for me.

**Review by MilkeeyCat — APPROVED** [review]
LGTM

**Review by Bamcane — APPROVED** [review]
Make it be merged here, ignore #89

**Comment by ChillerDragon** [comment]
Whats up with the auto merge? Something is stuck here -.-

**Comment by ChillerDragon** [comment]
Okay the check style stage did not run because another job already failed. I just triggered a rerun of the check style. It should work now :crossed_fingers:

**Pull request merged**
