### PR TITLE
Fixed cursor offset in the editor and removed brush display when picking tiles #3222

### PR DESCRIPTION
**Pull request by teeworlds-mirror**
upstream: https://www.github.com/teeworlds/teeworlds/pull/3222

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I am not aware of the bug that is being fixed here. @Bamcane could you upload a clip showcasing the bug and how it is fixed?

**Comment by Bamcane** [comment]
> I am not aware of the bug that is being fixed here. @Bamcane could you upload a clip showcasing the bug and how it is fixed?

@ChillerDragon
Image1
The brush displayed in the tilepicker.But we don't need it when we pick tile. 
Also, cursor offset because of teeworlds #3164
Robyt3 set a wrong value to `m_MouseWorldX` and `m_MouseWorldY`  `m_MouseWorldX = aPoints[0] + WorldWidth * (s_MouseX / UI()->Screen()->w);`
That make the cursor displayed offset like this
图片

**Comment by Bamcane** [comment]
I fixed it by setting `m_MouseWorldX` the right value

**Comment by ChillerDragon** [comment]
before:

https://github.com/teeworlds-community/teeworlds/assets/20344300/9f36ecfe-0e38-487a-8b1e-a9f5e6295957

after:




https://github.com/teeworlds-community/teeworlds/assets/20344300/7740ff46-6dad-4647-8b63-957bc3b91b0e


LGTM :+1:

**Review by ChillerDragon — APPROVED** [review]

**Review by Bamcane — APPROVED** [review]

**Review by ST-Chara — APPROVED** [review]

**Review by Hu1night — APPROVED** [review]

**Pull request merged**
